#!/bin/bash
#SBATCH -J auto-openmp16
#SBATCH -o auto-openmp16.%j.stdout
#SBATCH -e auto-openmp16.%j.error
#SBATCH -p normal
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 00:20:00
#SBATCH --mail-user=mattwilliams1515@gmail.com
#SBATCH --mail-type=all

rm openmp.txt
srun -n 1 -c 1 ./serial -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=1
srun -n 1 -c 1 ./openmp -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=2
srun -n 1 -c 2 ./openmp -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=4
srun -n 1 -c 4 ./openmp -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=8
srun -n 1 -c 8 ./openmp -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=16
srun -n 1 -c 16 ./openmp -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=2
srun -n 1 -c 2 ./openmp -n 1000 -no -s openmp.txt
export OMP_NUM_THREADS=4
srun -n 1 -c 4 ./openmp -n 2000 -no -s openmp.txt
export OMP_NUM_THREADS=8
srun -n 1 -c 8 ./openmp -n 4000 -no -s openmp.txt
export OMP_NUM_THREADS=16
srun -n 1 -c 16 ./openmp -n 8000 -no -s openmp.txt
./autograder -v openmp -s openmp.txt
